name: Discord Changelog

on:
  push:
    paths:
      - "CHANGELOG.md"
    branches:
      - main

jobs:
  send-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read CHANGELOG.md
        id: read_changelog
        run: |
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
          cat CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send CHANGELOG.md to Discord
        run: |
          curl -H "Content-Type: multipart/form-data" \
               -F 'payload_json={
                 "embeds": [{
                   "title": "Update pushed",
                   "description": "Full changelog available in the attached file.",
                   "color": 3447003
                 }]
               }' \
               -F "file=@CHANGELOG.md" \
               ${{ secrets.DISCORD_WEBHOOK }}
